name: Publish

on:
  pull_request:
    types:
      - closed
    branches: 
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Use NodeJS 16"
      uses: actions/setup-node@v3
      with:
        node-version: '16'
      
    - name: "Version and publish"
      run: |
        lerna version --conventional-commits --conventional-graduate --yes
        lerna publish from-git  --yes

